INSERT INTO authors (nome,sobrenome)
VALUES ("Sidney","Sheldon"),
("Pedro","Bandeira"),
("Raul","Drewnick"),
("Renato","Tapajós"),
("Ivan","Saraiva"),
("Hugo","Victor"),
("Arlene","Holanda"),
("George R.R","Martin"),
("J. Fernando","Pimentel"),
("Denise","Santos"),
("Osni Moura","Ribeiro"),
("Michael","Barrow"),
("Daniel A.","Wren"),
("Frank L.","Acuff"),
("Antonio Arnot","Crespo"),
("Armando Mellagi","Filho"),
("Rodney","Wernke"),
("Jorge","Duro"),
("J.R","Bonavita"),
("Partha","Dasgupta"),
("Petrônio Garcia","Martins"),
("Pablo Dall","Oglio"),
("Marco A.","Oliveira"),
("Rodrigo","Urubatan"),
("Paulo","Freire"),
("Gabriel","Bicalho"),
("Kabengele","Munanga"),
("Myriam Becho","Mota"),
("Malba","Tahan"),
("Cristiane","Dantas"),
("Myrian","Ellis"),
("Paulo Sérgio","Pinheiro"),
("Nelson Luís Bezerra","Campos"),
("Andréa","Rodrigues"),
("Ana Fernanda Gomes","Ascencio"),
("Ascencio","Gonçalves"),
("Henri","Wallon"),
("Ana Carolina","Carvalho"),
("Kathy","Sierra"),
("Carlos A.A.","Caruso"),
("Carlos Augusto","Lacerda"),
("Evanildo","Bechara"),
("Maureen","Cox"),
("Edgar Allan","Poe"),
("Felipe Nery Rodrigues","Machado"),
("Marcos Antônio","Cardoso"),
("César","Cool"),
("Sérgio","Furgeri"),
("Mauro De Salles","Villar"),
("Alice Cristina","Coleto"),
("Marcelo","Gaspar"),
("Diego","Pereira"),
("Nelson Luis Bezerra","Campos"),
("Carlos Alberto","Mucelin"),
("Francisco Heitor Simões","Gonçalves"),
("Ricardo R.","Lecheta"),
("Takeshy","Tachizawa"),
("Leila Maria Pinheiro","Fernandes"),
("José De Ávila Aguiar","Coimbra"),
("Gley Fabiano Cardoso","Xavier"),
("Oziel Moreira","Neto"),
("Jayr Figueiredo De","Oliveira"),
("Inácio","Arruda"),
("José","Pimentel"),
("John","Palfrey"),
("Governo Do Estado Do","Ceará"),
("Assef","Kfouri"),
("Newton","Fernandes"),
("Lúcio","Alcântara"),
("Eça De","Queiroz"),
("José De","Alencar"),
("Joaquim Manuel","De Macedo"),
("Joao Cabral","De Melo Neto"),
("Paulo","Leminski"),
("Olavo","Bilac"),
("Machado De","Assis"),
("Bartolomeu Campos De","Queirós"),
("Manoel De","Barros"),
("Maria","Quintana"),
("Vinicius De","Moraes"),
("Tarcísio","Matos"),
("João Cabral De Melo","Neto"),
("Luis","Camões"),
("Cesár Roberto Leite Da","Silva"),
("Celso","Antunes"),
("Lima","Barreto"),
("Tesuko","Oda"),
("Peter F.","Drucker"),
("Fátima Maria Gondim Bezerra","Farias"),
("Fausto","Cunha"),
("Mario","Quintana"),
("Bernardo","Guimarães"),
("Aluísio","Azevedo"),
("Camilo Castelo","Branco"),
("Mário De","Andrade"),
("Sérgio De Castro","Pinto"),
("Alexandre","Herculano"),
("Paulo","Pessoa"),
("Carlos Heitor","Cony"),
("Gregório De","Matos"),
("Augusto Dos","Anjos"),
("Pedro Alaim Martins Garcia","Júnior"),
("Lêdo","Ivo"),
("Raul","Bopp"),
("José Paulo","Paes"),
("Luis Fernando","Verissimo"),
("Fernando","Sabino"),
("Ondjaki",null),
("Paulo Henriques","Brito"),
("José Américo De","Almeida"),
("Lygia Fagundes","Telles"),
("Moacyr","Scliar"),
("Orlando Villas","Bôas"),
("Antônio De Alcântara","Machado"),
("Bocage Manuel Maria","Barbosa"),
("Ribamar","Fonseca"),
("Geni","Guimarães"),
("Oliveira","Paiva"),
("Álvares","De Azevedo"),
("Adolfo","Caminha"),
("Euclides","Da Cunha"),
("Linhares","Filho"),
("Samir","Thomaz"),
("Henriqueta","Lisboa"),
("Zélia","Gattai"),
("José Eduardo","Agualusa"),
("Pedro","Lyra"),
("José Adelino","Medeiros"),
("Filgueiras","Lima"),
("Fernando","Pessoa"),
("José Leite","Netto"),
("Júlio","Ribeiro"),
("Domingos","Olímpio"),
("Manuel","Bandeira"),
("Miguel","Torga"),
("Manuel","Rui"),
("Mia","Couto"),
("Rachel De","Queiroz"),
("Pabo","Neruda"),
("Maria Josenice","Pinto"),
("João","Proteti"),
("Caio Porfirio","Carneiro"),
("Roniwalter","Jatobá"),
("Vera Maria Tietzmann","Silva"),
("Geraldo","Carneiro"),
("Renato","Rocha"),
("Affonso Romano De","Sant'Anna"),
("Drauzio","Varella"),
("Joao Ubaldo","Ribeiro"),
("João De Jesus Paes","Loureiro"),
("Fernando R. De Moraes","Barros"),
("Aluísio","Azevedo"),
("Artur Bispo Dos Santos","Neto"),
("Valdir","Santiago"),
("Charles","Auffray"),
("Maria Cândida","Moraes"),
("Nelio","Bizzo"),
("Raymundo","Neto"),
("Herman","Lima"),
("Fabrício","Corsaletti"),
("Raul","Drewnick"),
("Francisco Teixeira Celso","Frederico"),
("Josué","Montello"),
("Leonardo","Boff"),
("Riosângela Doin De","Almeida"),
("Antônio","Rezende"),
("José Lins Do","Rego"),
("Erico","Verissimo"),
("Roberto","Giansanti"),
("Bruno Berlendis","De Carvalho"),
("Carla Teodoro","Costa"),
("João","Antônio"),
("Vinicius","De Figueiredo"),
("Dionisio","Jacob"),
("Castro","Alves"),
("Maria Valéria","Rezende"),
("Maria José","Dupré"),
("André","Botelho"),
("Eliane","Ganem"),
("Edgar","Morin"),
("Alcione","Araújo"),
("Eça De","Queirós"),
("Carlos Drummond De","Andrade"),
("Cláudia","Fares"),
("Heloisa","Seixas"),
("Cora","Coralina"),
("Horácio","Dídimo"),
("Adriano","Espínola"),
("Edmar","Freitas"),
("Flora","Figueiredo"),
("Tiago Moreira","Gomes")
