INSERT INTO editoras(nome) VALUES
("Record"),
("Leya"),
("Novo Conceito"),
("Moderna"),
("Aleph"),
("Ática"),
("Moitará"),
("Senac"),
("Érica"),
("Novatec"),
("Saraiva"),
("Atlas"),
("Smile"),
("Autêntica"),
("Difusão Cultural Do Livro"),
("Literatura Para Todos"),
("Lucerna"),
("Paz E Terra"),
("Brasil"),
("Lexikon"),
("Nova Fronteira"),
("Livro Técnico"),
("Alta Books"),
("Disal"),
("Fgv"),
("Universo Dos Livros"),
("Artmed"),
("Bertrand Brasil"),
("Maza Edições"),
("Digerati Books"),
("Maza Edições"),
("Martins Fontes"),
("Pearson"),
("Livros Da Raposa Vermelha"),
("Moderna"),
("Editora Do Livro Técnico"),
("Érica"),
("Revista Dos Tribunais"),
("Senado Federal"),
("Lu Fernandes"),
("Demócrito Rocha"),
("Dim.Ce"),
("Grupo A"),
("Brink Brasil"),
("Objetiva"),
("Edições Câmara"),
("Gaia"),
("Planeta Do Brasil"),
("Globo"),
("Schwarcz"),
("Mentoria Das Letras"),
("Odysseus"),
("Claroenigma"),
("Vozes"),
("Pioneira Thomson Learning"),
("Escrituras Editora"),
("Demócrito Rocha"),
("Best Seller"),
("Global"),
("Helvética Editorial"),
("Vida Melhor"),
("Geográfica"),
("Ibep"),
("Ediouro Publicações"),
("Martin Claret"),
("diouro Publicações"),
("Bicbanco"),
("José Olympio"),
("Casa De Palavras"),
("Gaudí Editorial"),
("Agir Editora"),
("Frente"),
("Gráfica Bernardi"),
("Kuarup"),
("Cejup"),
("Abc"),
("Universidade Federal Do Ceará"),
("Aymará"),
("Mercado Aberto"),
("Expressão Gráfica"),
("Brasiliense"),
("Rhj"),
("Gryphus"),
("Siciliano"),
("Papirus"),
("Nova Alexandria Ltda"),
("Companhia Das Letras"),
("Rocco"),
("Ponteio"),
("Lepm"),
("Insitituto Piaget"),
("Alfaguara"),
("Cortez"),
("Cultural Brasil"),
("Escala Educacional"),
("A Página"),
("Contexto"),
("Lacerda"),
("Berlendis E Vertecchia"),
("Civilização Brasileira"),
("Zahar"),
("Fontanar"),
("Comboio De Corda"),
("Abril Educação"),
("Instituto Callis"),
("Klick"),
("Cosacnaify"),
("Topbooks"),
("Sulina"),
("Editora Do Brasil"),
("Nova Espiral"),
("Ufc"),
("Instituto Lukács"),
("Premius"),
("Novo Século"),
("Editora Scipione"),
("Sas")
